"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useSession } from "next-auth/react";
import { InstrumentCategoryManager } from "@/components/instruments/InstrumentCategoryManager";
import { InstrumentForm } from "@/components/instruments/InstrumentForms";

type Instrument = { id: string; name: string; categoryId: string; brand?: string | null; model?: string | null; assetNumber?: string | null; status: "ACTIVE" | "MAINTENANCE" | "INACTIVE"; category: { name: string }; ministry?: { name: string } | null };
type Result = { instruments: Instrument[]; pagination: { total: number } };
type Api = { success: boolean; data?: Result; error?: { message?: string } };
const labels: Record<Instrument["status"], string> = { ACTIVE: "Ativo", MAINTENANCE: "Em manutencao", INACTIVE: "Inativo" };
const colors: Record<Instrument["status"], string> = { ACTIVE: "bg-emerald-100 text-emerald-800", MAINTENANCE: "bg-amber-100 text-amber-800", INACTIVE: "bg-slate-100 text-slate-700" };

export function InstrumentManager() {
  const { data: session } = useSession(); const permissions = session?.user.permissionCodes ?? [];
  const [data, setData] = useState<Result>(); const [search, setSearch] = useState(""); const [form, setForm] = useState<Instrument | null | undefined>(); const [categories, setCategories] = useState(false); const [message, setMessage] = useState("");
  const query = useMemo(() => new URLSearchParams({ search, pageSize: "20" }).toString(), [search]);
  const load = useCallback(async () => { const response = await fetch(`/api/instruments?${query}`, { cache: "no-store" }); const result = await response.json() as Api; if (result.success) setData(result.data); else setMessage(result.error?.message ?? "Nao foi possivel carregar instrumentos."); }, [query]);
  useEffect(() => { void load(); }, [load]);
  async function remove(id: string) { if (!confirm("Excluir este instrumento? O historico sera preservado.")) return; const response = await fetch(`/api/instruments/${id}`, { method: "DELETE" }); const result = await response.json() as Api; if (!result.success) setMessage(result.error?.message ?? "Nao foi possivel excluir."); else { setMessage("Instrumento excluido. O historico foi preservado."); void load(); } }
  return <div className="space-y-5"><div className="flex flex-col gap-3 rounded-md border border-hope-100 bg-white p-4 sm:flex-row sm:items-end sm:justify-between"><label className="grid gap-1 text-xs font-bold uppercase tracking-wide text-ink-500">Pesquisar<input className="rounded-md border border-hope-100 px-3 py-2 text-sm" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Nome, marca, modelo, serie ou patrimonio" /></label><div className="flex gap-2">{permissions.includes("instrument.create") && <button className="rounded-md bg-hope-600 px-4 py-2 text-sm font-bold text-white" onClick={() => setForm(null)}>Novo instrumento</button>}{permissions.includes("instrument.category.manage") && <button className="rounded-md border border-hope-200 px-4 py-2 text-sm font-bold" onClick={() => setCategories(true)}>Categorias</button>}</div></div>{message && <p className="rounded-md bg-hope-50 p-3 text-sm">{message}</p>}<div className="overflow-x-auto rounded-md border border-hope-100 bg-white"><table className="min-w-full text-sm"><thead className="bg-hope-50 text-left"><tr><th className="p-3">Nome</th><th className="p-3">Categoria</th><th className="p-3">Marca / Modelo</th><th className="p-3">Patrimonio</th><th className="p-3">Ministerio</th><th className="p-3">Situacao</th><th className="p-3">Acoes</th></tr></thead><tbody>{data?.instruments.map((instrument) => <tr className="border-t" key={instrument.id}><td className="p-3 font-semibold"><Link href={`/instrumentos/${instrument.id}`}>{instrument.name}</Link></td><td className="p-3">{instrument.category.name}</td><td className="p-3">{[instrument.brand, instrument.model].filter(Boolean).join(" / ") || "-"}</td><td className="p-3">{instrument.assetNumber || "-"}</td><td className="p-3">{instrument.ministry?.name || "-"}</td><td className="p-3"><span className={`rounded px-2 py-1 text-xs font-bold ${colors[instrument.status]}`}>{labels[instrument.status]}</span></td><td className="p-3"><div className="flex gap-2"><Link className="font-bold" href={`/instrumentos/${instrument.id}`}>Detalhes</Link>{permissions.includes("instrument.update") && <button className="font-bold" onClick={() => setForm(instrument)}>Editar</button>}{permissions.includes("instrument.delete") && <button className="font-bold text-red-700" onClick={() => void remove(instrument.id)}>Excluir</button>}</div></td></tr>)}{!data?.instruments.length && <tr><td colSpan={7} className="p-8 text-center">Nenhum instrumento encontrado.</td></tr>}</tbody></table></div><p className="text-sm text-ink-500">{data?.pagination.total ?? 0} instrumento(s)</p>{categories && <InstrumentCategoryManager onClose={() => setCategories(false)} />}{form !== undefined && <InstrumentForm initial={form ?? undefined} onClose={() => setForm(undefined)} onSaved={() => { setMessage(form ? "Instrumento atualizado com sucesso." : "Instrumento cadastrado com sucesso."); void load(); }} />}</div>;
}