import { ScheduleStatus } from "@prisma/client";
import { AppError } from "@/lib/errors";
import { scheduleRepository, scheduleSongRepository } from "@/repositories";
import type { ScheduleSongCopyInput, ScheduleSongCreateInput, ScheduleSongUpdateInput } from "@/validators";

function serialize<T extends { createdAt: Date; updatedAt: Date }>(item: T) { return { ...item, createdAt: item.createdAt.toISOString(), updatedAt: item.updatedAt.toISOString() }; }
async function scheduleOrThrow(id: string) { const schedule = await scheduleRepository.findById(id); if (!schedule) throw new AppError("Escala nao encontrada.", 404, "SCHEDULE_NOT_FOUND"); return schedule; }
export const scheduleSongService = {
  async list(scheduleId: string) { const schedule = await scheduleOrThrow(scheduleId); const [songs, members, sources] = await Promise.all([scheduleSongRepository.list(scheduleId), scheduleSongRepository.listScheduleMembers(scheduleId), scheduleSongRepository.listSourceSchedules(scheduleId, schedule.ministry.id)]); return { songs: songs.map(serialize), members: members.map((item) => item.member), sources: sources.map((item) => ({ id: item.id, title: item.title, date: item.date.toISOString(), songCount: item._count.songs })) }; },
  async add(scheduleId: string, input: ScheduleSongCreateInput, userId: string) { const schedule = await scheduleOrThrow(scheduleId); if (schedule.status === ScheduleStatus.COMPLETED || schedule.status === ScheduleStatus.CANCELED) throw new AppError("Esta escala nao pode receber repertorio.", 409, "SCHEDULE_LOCKED"); if (!(await scheduleSongRepository.findActiveSong(input.songId))) throw new AppError("Musica ativa nao encontrada.", 404, "SONG_NOT_FOUND"); if (await scheduleSongRepository.findSongDuplicate(scheduleId, input.songId)) throw new AppError("Esta musica ja esta no repertorio.", 409, "SCHEDULE_SONG_DUPLICATED"); if (input.leadMemberId && !(await scheduleSongRepository.listScheduleMembers(scheduleId)).some((item) => item.member.id === input.leadMemberId)) throw new AppError("O ministro deve ser participante ativo da escala.", 400, "INVALID_LEAD_MEMBER"); const position = input.position || ((await scheduleSongRepository.maxPosition(scheduleId))._max.position ?? 0) + 1; return serialize(await scheduleSongRepository.create(scheduleId, { ...input, position }, userId)); },
  async update(scheduleId: string, id: string, input: ScheduleSongUpdateInput, userId: string) { const schedule = await scheduleOrThrow(scheduleId); if (schedule.status === ScheduleStatus.COMPLETED || schedule.status === ScheduleStatus.CANCELED) throw new AppError("Esta escala nao pode ser alterada.", 409, "SCHEDULE_LOCKED"); const current = await scheduleSongRepository.findById(scheduleId, id); if (!current) throw new AppError("Musica do repertorio nao encontrada.", 404, "SCHEDULE_SONG_NOT_FOUND"); if (input.songId && await scheduleSongRepository.findSongDuplicate(scheduleId, input.songId, id)) throw new AppError("Esta musica ja esta no repertorio.", 409, "SCHEDULE_SONG_DUPLICATED"); if (input.leadMemberId && !(await scheduleSongRepository.listScheduleMembers(scheduleId)).some((item) => item.member.id === input.leadMemberId)) throw new AppError("O ministro deve ser participante ativo da escala.", 400, "INVALID_LEAD_MEMBER"); if (input.position && await scheduleSongRepository.findActivePosition(scheduleId, input.position, id)) throw new AppError("Ja existe uma musica nessa posicao.", 409, "SCHEDULE_SONG_POSITION_DUPLICATED"); return serialize(await scheduleSongRepository.update(id, input, userId)); },
  async remove(scheduleId: string, id: string, userId: string) { const schedule = await scheduleOrThrow(scheduleId); if (schedule.status === ScheduleStatus.COMPLETED || schedule.status === ScheduleStatus.CANCELED) throw new AppError("Esta escala nao pode ser alterada.", 409, "SCHEDULE_LOCKED"); if (!(await scheduleSongRepository.findById(scheduleId, id))) throw new AppError("Musica do repertorio nao encontrada.", 404, "SCHEDULE_SONG_NOT_FOUND"); return scheduleSongRepository.softDeleteAndRecompact(scheduleId, id, userId); },
  async reorder(scheduleId: string, id: string, direction: "up" | "down", userId: string) { await scheduleOrThrow(scheduleId); await scheduleSongRepository.reorder(scheduleId, id, direction, userId); return this.list(scheduleId); },
  async copy(scheduleId: string, input: ScheduleSongCopyInput, userId: string) { const destination = await scheduleOrThrow(scheduleId); const source = await scheduleOrThrow(input.sourceScheduleId); if (scheduleId === input.sourceScheduleId) throw new AppError("A escala origem e destino devem ser diferentes.", 400, "INVALID_SOURCE_SCHEDULE"); if (destination.ministry.id !== source.ministry.id) throw new AppError("A escala origem deve ser do mesmo ministerio.", 400, "INVALID_SOURCE_SCHEDULE"); if (destination.status === ScheduleStatus.COMPLETED || destination.status === ScheduleStatus.CANCELED) throw new AppError("A escala destino nao pode receber repertorio.", 409, "SCHEDULE_LOCKED"); const [sourceItems, destinationItems] = await Promise.all([scheduleSongRepository.listForCopy(input.sourceScheduleId), scheduleSongRepository.list(scheduleId)]); if (sourceItems.some((item) => item.song.deletedAt || !item.song.isActive)) throw new AppError("A escala origem possui uma musica inativa ou removida do catalogo.", 409, "SONG_NOT_AVAILABLE"); if (input.mode === "append" && sourceItems.some((item) => destinationItems.some((existing) => existing.song.id === item.songId))) throw new AppError("A escala destino ja possui uma ou mais musicas do repertorio origem.", 409, "SCHEDULE_SONG_DUPLICATED"); await scheduleSongRepository.copy(scheduleId, input.sourceScheduleId, input.mode, userId); return this.list(scheduleId); }
};
