"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useSession } from "next-auth/react";
import { FormMessage } from "@/components/ui/FormMessage";
import { musicKeys } from "@/utils/music";
import type { SongFormValues, SongListResult, SongSummary } from "@/types";

type Api<T> = { success: true; data: T } | { success: false; error: { message: string } };
const empty: SongFormValues = { title: "", artist: "", youtubeUrl: "", referenceKey: "", resourceUrl: "", simplifiedResourceUrl: "", notes: "", isActive: true };
const input = "w-full rounded-md border border-hope-100 px-3 py-2 text-sm font-semibold text-ink-800 outline-none focus:border-hope-500 focus:ring-2 focus:ring-hope-100";
function date(value: string) { return new Intl.DateTimeFormat("pt-BR").format(new Date(value)); }
export function SongManager() {
  const { data: session } = useSession();
  const permissions = session?.user.permissionCodes ?? [];
  const canCreate = permissions.includes("song.create");
  const canUpdate = permissions.includes("song.update");
  const canDelete = permissions.includes("song.delete");
  const [data, setData] = useState<SongListResult | null>(null); const [form, setForm] = useState(empty); const [editing, setEditing] = useState<string | null>(null); const [open, setOpen] = useState(false); const [message, setMessage] = useState(""); const [formMessage, setFormMessage] = useState(""); const [search, setSearch] = useState("");
  const query = useMemo(() => new URLSearchParams({ search, pageSize: "10" }).toString(), [search]);
  async function load() { const response = await fetch(`/api/songs?${query}`, { cache: "no-store" }); const payload = await response.json() as Api<SongListResult>; if (payload.success) setData(payload.data); else setMessage(payload.error.message); }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load(); }, [query]);
  function start(song?: SongSummary) { setEditing(song?.id ?? null); setForm(song ? { title: song.title, artist: song.artist ?? "", youtubeUrl: song.youtubeUrl ?? "", referenceKey: song.referenceKey ?? "", resourceUrl: song.resourceUrl ?? "", simplifiedResourceUrl: song.simplifiedResourceUrl ?? "", notes: song.notes ?? "", isActive: song.isActive } : empty); setMessage(""); setFormMessage(""); setOpen(true); }
  async function save(event: FormEvent) { event.preventDefault(); setFormMessage(""); const response = await fetch(editing ? `/api/songs/${editing}` : "/api/songs", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const payload = await response.json() as Api<unknown>; if (!payload.success) { setFormMessage(payload.error.message); return; } setOpen(false); setMessage("Musica salva com sucesso."); await load(); }
  async function remove(id: string) { if (!window.confirm("Deseja remover esta musica?")) return; const response = await fetch(`/api/songs/${id}`, { method: "DELETE" }); const payload = await response.json() as Api<unknown>; if (!payload.success) { setMessage(payload.error.message); return; } setMessage("Musica removida."); await load(); }
  function update<K extends keyof SongFormValues>(key: K, value: SongFormValues[K]) { setForm((current) => ({ ...current, [key]: value })); }
  return <div className="space-y-5">
    <div className="flex flex-col gap-3 rounded-md border border-hope-100 bg-white p-4 shadow-sm sm:flex-row sm:items-end sm:justify-between"><label className="grid gap-1 text-xs font-bold uppercase tracking-wide text-ink-500">Pesquisar<input className={input} value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Titulo ou artista" /></label><button type="button" disabled={!canCreate} onClick={() => start()} className="rounded-md bg-hope-600 px-4 py-2 text-sm font-bold text-white">Nova musica</button></div>
    {message ? <div className="rounded-md border border-hope-100 bg-hope-50 px-4 py-3 text-sm font-semibold text-ink-800">{message}</div> : null}
    <div className="overflow-hidden rounded-md border border-hope-100 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-hope-50 text-left text-xs font-bold uppercase tracking-wide text-ink-500"><tr><th className="px-4 py-3">Musica</th><th className="px-4 py-3">Tom</th><th className="px-4 py-3">Uso</th><th className="px-4 py-3">Ultima utilizacao</th><th className="px-4 py-3 text-right">Acoes</th></tr></thead><tbody className="divide-y divide-hope-100">{data?.songs.map((song) => <tr key={song.id}><td className="px-4 py-4"><p className="font-semibold text-ink-900">{song.title}</p><p className="text-xs text-ink-500">{song.artist || "Artista nao informado"}</p></td><td className="px-4 py-4">{song.referenceKey || "-"}</td><td className="px-4 py-4">{song.usageCount}</td><td className="px-4 py-4">{song.lastUsedAt ? date(song.lastUsedAt) : "-"}</td><td className="px-4 py-4 text-right"><div className="flex flex-wrap justify-end gap-2"><button disabled={!canUpdate} className="rounded-md border border-hope-100 px-3 py-2 text-xs font-bold disabled:opacity-40" onClick={() => start(song)}>Editar</button><button disabled={!canDelete} className="rounded-md border border-hope-100 px-3 py-2 text-xs font-bold disabled:opacity-40" onClick={() => remove(song.id)}>Remover</button></div></td></tr>)}{!data?.songs.length ? <tr><td colSpan={5} className="px-4 py-8 text-center font-semibold text-ink-500">Nenhuma musica encontrada.</td></tr> : null}</tbody></table></div>{data?.pagination ? <div className="border-t border-hope-100 px-4 py-3 text-sm text-ink-600">{data.pagination.total} musica(s)</div> : null}</div>
    {open ? <div className="fixed inset-0 z-40 overflow-y-auto bg-ink-900/45 px-4 py-6"><div className="mx-auto max-w-2xl rounded-md bg-white shadow-soft"><form onSubmit={save}><div className="flex items-start justify-between border-b border-hope-100 px-5 py-4"><h2 className="text-lg font-bold text-ink-900">{editing ? "Editar musica" : "Nova musica"}</h2><button type="button" onClick={() => setOpen(false)} className="rounded-md border border-hope-100 px-3 py-2 text-sm font-bold">Fechar</button></div><div className="grid gap-4 p-5 md:grid-cols-2"><div className="md:col-span-2"><FormMessage id="song-form-message">{formMessage}</FormMessage></div><Field label="Titulo"><input required className={input} value={form.title} onChange={(e) => update("title", e.target.value)} /></Field><Field label="Artista"><input className={input} value={form.artist ?? ""} onChange={(e) => update("artist", e.target.value)} /></Field><Field label="Tom de referencia"><select className={input} value={form.referenceKey ?? ""} onChange={(e) => update("referenceKey", e.target.value)}><option value="">Nao informado</option>{musicKeys.map((key) => <option key={key}>{key}</option>)}</select></Field><Field label="Link do YouTube"><input type="url" className={input} value={form.youtubeUrl ?? ""} onChange={(e) => update("youtubeUrl", e.target.value)} /></Field><Field label="Material"><input type="url" className={input} value={form.resourceUrl ?? ""} onChange={(e) => update("resourceUrl", e.target.value)} /></Field><Field label="Versao simplificada"><input type="url" className={input} value={form.simplifiedResourceUrl ?? ""} onChange={(e) => update("simplifiedResourceUrl", e.target.value)} /></Field><Field label="Observacoes" className="md:col-span-2"><textarea className={`${input} min-h-24`} value={form.notes ?? ""} onChange={(e) => update("notes", e.target.value)} /></Field><button type="button" onClick={() => window.open(`https://www.youtube.com/results?search_query=${encodeURIComponent(`${form.title} ${form.artist ?? ""}`)}`, "_blank", "noopener,noreferrer")} className="w-fit rounded-md border border-hope-100 px-3 py-2 text-sm font-bold">Pesquisar no YouTube</button><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={form.isActive} onChange={(e) => update("isActive", e.target.checked)} />Ativa</label></div><div className="flex justify-end gap-3 border-t border-hope-100 px-5 py-4"><button type="button" onClick={() => setOpen(false)} className="rounded-md border border-hope-100 px-4 py-2 text-sm font-bold">Cancelar</button><button className="rounded-md bg-hope-600 px-4 py-2 text-sm font-bold text-white">Salvar</button></div></form></div></div> : null}
  </div>;
}
function Field({ label, children, className = "" }: { label: string; children: React.ReactNode; className?: string }) { return <label className={`grid gap-1 text-xs font-bold uppercase tracking-wide text-ink-500 ${className}`}>{label}{children}</label>; }
