-- CreateEnum
CREATE TYPE "PushNotificationSkipReason" AS ENUM ('ALREADY_SUCCEEDED_IN_LATER_ATTEMPT', 'SUBSCRIPTION_NOT_FOUND', 'SUBSCRIPTION_INACTIVE', 'DEVICE_ALREADY_REMOVED', 'ENDPOINT_HASH_CHANGED', 'USER_INACTIVE', 'DEVICE_OWNER_CHANGED', 'NO_LONGER_ELIGIBLE', 'UNKNOWN');

-- AlterTable
ALTER TABLE "PushNotificationLogDevice"
ALTER COLUMN "skipReason" TYPE "PushNotificationSkipReason"
USING CASE
  WHEN "skipReason" IS NULL OR "skipReason" = '' THEN NULL
  WHEN "skipReason" IN ('ALREADY_SUCCEEDED_IN_LATER_ATTEMPT', 'SUBSCRIPTION_NOT_FOUND', 'SUBSCRIPTION_INACTIVE', 'DEVICE_ALREADY_REMOVED', 'ENDPOINT_HASH_CHANGED', 'USER_INACTIVE', 'DEVICE_OWNER_CHANGED', 'NO_LONGER_ELIGIBLE', 'UNKNOWN') THEN "skipReason"::"PushNotificationSkipReason"
  ELSE 'UNKNOWN'::"PushNotificationSkipReason"
END;
