import { Prisma } from "@prisma/client";
import { prisma } from "@/prisma/client";
import type { InstrumentCreateInput, InstrumentListQueryInput, InstrumentUpdateInput } from "@/validators";
const select={id:true,name:true,brand:true,model:true,serialNumber:true,assetNumber:true,acquisitionDate:true,acquisitionValue:true,status:true,ministryId:true,categoryId:true,notes:true,createdAt:true,updatedAt:true,category:{select:{id:true,name:true,isActive:true}},ministry:{select:{id:true,name:true,isActive:true}}} satisfies Prisma.InstrumentSelect;
export type InstrumentRecord=Prisma.InstrumentGetPayload<{select:typeof select}>;
export const instrumentRepository={
 async list(f:InstrumentListQueryInput){const where:Prisma.InstrumentWhereInput={deletedAt:null,...(f.search?{OR:[{name:{contains:f.search,mode:"insensitive"}},{brand:{contains:f.search,mode:"insensitive"}},{model:{contains:f.search,mode:"insensitive"}},{serialNumber:{contains:f.search,mode:"insensitive"}},{assetNumber:{contains:f.search,mode:"insensitive"}}]}:{}),...(f.categoryId?{categoryId:f.categoryId}:{}),...(f.ministryId?{ministryId:f.ministryId}:{}),...(f.status?{status:f.status}:{})};const skip=(f.page-1)*f.pageSize;const [instruments,total]=await prisma.$transaction([prisma.instrument.findMany({where,select,orderBy:{[f.sortBy]:f.sortOrder},skip,take:f.pageSize}),prisma.instrument.count({where})]);return{instruments,total};},
 findById(id:string){return prisma.instrument.findFirst({where:{id,deletedAt:null},select});}, findExistingSerialNumber(serialNumber:string,ignoreId?:string){return prisma.instrument.findFirst({where:{serialNumber,...(ignoreId?{id:{not:ignoreId}}:{})},select:{id:true}});}, findExistingAssetNumber(assetNumber:string,ignoreId?:string){return prisma.instrument.findFirst({where:{assetNumber,...(ignoreId?{id:{not:ignoreId}}:{})},select:{id:true}});},
 create(data:InstrumentCreateInput,userId:string){return prisma.instrument.create({data:{...data,createdById:userId,updatedById:userId},select});}, update(id:string,data:InstrumentUpdateInput,userId:string){return prisma.instrument.update({where:{id},data:{...data,updatedById:userId},select});}, softDelete(id:string,userId:string){return prisma.instrument.update({where:{id},data:{deletedAt:new Date(),updatedById:userId},select:{id:true}});}
};
